### ISSUE TITLE
New istallation got Error

### ISSUE THREAD

**Issue by dev-dx** [nocio/headstart#11]
Hi,

I just installed the plugin, and tried to test the API by adding a user schema from the template on github.
When I do an API test, I get the following error response:

  "errors": [
    {
      "debugMessage": "Undefined index: SystemFile",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "__schema",
        "types"
      ],
I have no idea, Is there something wrong with the configuration that I made?

**Comment by frthjf** [comment]
Hi @dev-dx,

The error message indicates that the GraphQL SystemFile is undefined that used by the user type [here](https://github.com/nocio/headstart/blob/master/templates/rainlab_user.htm#L15). The SystemFile Type is defined in the [core_cms](https://github.com/nocio/headstart/blob/master/templates/core_cms.htm#L37) so if you install that template as well the error should go away. 

However, I can see that this is confusing for new users, so I'll comment it out in the template so that it will work out of the box in future.

Thanks for reporting. Let me know if you encounter any other issue.
