### ISSUE TITLE
auth_token header in spa/pwa app

### ISSUE THREAD

**Issue by mitjarobic** [nocio/headstart#2]
Hi, 

I am using your auth.htm template. If I login from the integrated GraphiQL client the token/cookie is sent back from in the response headers. But, if I login from a vue spa/pwa app the respone headers do not have the auth_token. 

Any ideas how to solve the problem?

**Comment by frthjf** [comment]
Hi @mitjarobic, thanks for using my plugin. There are three reasons that I can think of that all have to do with the security of cookie tokens: 
1. The cookie is only send via SSL, not via unencrypted connections. If your development server does not use an SSL connection, you can set [this](https://github.com/nocio/headstart/blob/ac28bd28bd1bbcdea3c6932457e6b64a63eae174/templates/rluders_jwtauth/schema.htm#L50) parameter to false during development.
2. The cookie is httpOnly, meaning it's only accessible for the server and not through Javascript to prevent certain [XSS attacks](https://blog.codinghorror.com/protecting-your-cookies-httponly/). [This can be changed here, but shouldn't be changed](https://github.com/nocio/headstart/blob/ac28bd28bd1bbcdea3c6932457e6b64a63eae174/templates/rluders_jwtauth/schema.htm#L51).
3. Your SPA might live under a different domain, so the cookie is not set because of the [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy. In that case, you can install one of [these plugins](https://octobercms.com/plugins?search=cors).

Hope that helps! Let me know if it does not solve your problem.

**Comment by frthjf** [comment]
Marking this as fixed. Please re-open if you encounter any further issues.
