### ISSUE TITLE
Method Symfony\Component\HttpFoundation\Cookie::__toString() must not throw an exception, caught ErrorException: Array to string conversion

### ISSUE THREAD

**Issue by SebastiaanKloos** [nocio/headstart#5]
Your plugin breaks the RainLab.User plugin. See GIF attached.

```
Symfony\Component\Debug\Exception\FatalErrorException: Method Symfony\Component\HttpFoundation\Cookie::__toString() must not throw an exception, caught ErrorException: Array to string conversion
```

![CleanShot 2019-11-12 at 11 59 56](https://user-images.githubusercontent.com/6506510/69234282-104e0980-0b8f-11ea-8dd7-4a7a671cd3c8.gif)

**Comment by frthjf** [comment]
Hi Sebastiaan, 

I'm sorry you are experiencing this issue. I'll try and reproduce the problem now and keep you posted.

**Comment by frthjf** [comment]
Turns out the problem is not a direct problem with Headstart but a consequence of the dependencies of the Lighthouse server. It triggers an upgrade of the Symphony framework, which in turn leads to this [known breaking change](https://github.com/laravel/framework/issues/19443). 

The source of the error then is line 617 in ``vendor/october/rain/src/Auth/Manager.php``:
```
Cookie::queue(Cookie::forever($this->sessionKey, $toPersist));
```
where ``$toPersist`` is an array and the implicit string conversion fails.

I'm afraid this can only be resolved through the planned [move to Laravel 6](https://github.com/octobercms/october/issues/4381) which will bump the Symphony dependency. 

As a workaround, you have two options: 
- disable 'remember me' or comment out the line 617 that produces the error
- downgrade to Headstart 1.0.1 that does not upgrade the dependency

I hope this helps.
